services:
  db:
    image: postgres:16
    container_name: postgres_cookbook
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cookbook_docker
    volumes:
      - ./data:/var/lib/postgresql/data